name: 📦 Package Maps

on:
  release:
    types: [published]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip HW1_maps
        run: |
          zip -r Homeworld-HW1-maps-${{ github.event.release.tag_name }}.zip HW1_maps

      - name: Zip CATA_map
        run: |
          zip -r Homeworld-CATA-maps-${{ github.event.release.tag_name }}.zip CATA_map

      - name: Upload Homeworld-HW1-maps ZIP
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Homeworld-HW1-maps-${{ github.event.release.tag_name }}.zip
          asset_name: Homeworld-HW1-maps-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Homeworld-CATA-maps ZIP
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Homeworld-CATA-maps-${{ github.event.release.tag_name }}.zip
          asset_name: Homeworld-CATA-maps-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
